import { ThemeProvider } from "@mui/material";
import "./globals.css";
import { NextIntlClientProvider, AbstractIntlMessages } from "next-intl";
import { notFound } from "next/navigation";
import DarkThemeProvider from "@/components/DarkThemeProvider";

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

const locales = ["en", "ch"];

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export default async function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: "en" };
}) {
  if (!locales.includes(locale as any)) notFound();

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider locale={locale} messages={{ title: "title" }}>
          <DarkThemeProvider>{children}</DarkThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
