import { Inter } from 'next/font/google'
import './globals.css'
import { NextIntlClientProvider,  AbstractIntlMessages } from "next-intl";
import { notFound } from "next/navigation";

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export function generateStaticParams() {
  return [{locale: 'en'}];
}

export default async function LocaleLayout({
  children,
  params: {locale}
}: {
  children: React.ReactNode,
  params: {locale: 'en'}
}) {

  let messages: AbstractIntlMessages | undefined;

  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
    return (
      <html lang="en">
      <body className={inter.className}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
    )
  } catch (error) {
    notFound();
  }
}
